"""
BAYREUTHWING — Dynamic Analysis Rules Engine

Hot-loadable, self-tuning rule engine that evolves at runtime.
Rules can be loaded from YAML/JSON files, generated by the adaptive
learning system, or created from internet-discovered vulnerability patterns.

Key Features:
    - Hot-reload rules without restarting the scanner
    - Per-rule effectiveness tracking (TP/FP rates)
    - Auto-disable rules with high false positive rates
    - Auto-promote rules with high true positive rates
    - Conditional rules (framework-specific, language-specific)
    - Parameterized rule templates
    - Integration with adaptive learning for priority adjustment

Architecture:
    ┌──────────────────────────┐
    │  DynamicRuleEngine       │
    │  - load_rules()          │
    │  - scan(code, lang)      │
    │  - hot_reload()          │
    └──────────┬───────────────┘
               │
    ┌──────────▼───────────────┐
    │  DynamicRule             │
    │  - pattern               │
    │  - conditions            │
    │  - effectiveness tracker │
    └──────────┬───────────────┘
               │
    ┌──────────▼───────────────┐
    │  RuleEffectivenessTracker│
    │  - record_hit/miss       │
    │  - TP/FP rates           │
    │  - auto-tune decisions   │
    └──────────────────────────┘
"""

import json
import os
import re
import time
import hashlib
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional
from enum import Enum, auto


class RuleStatus(Enum):
    """Lifecycle status of a dynamic rule."""
    ACTIVE = auto()
    DISABLED = auto()        # Too many false positives
    PROMOTED = auto()        # Consistently high true positive rate
    EXPERIMENTAL = auto()    # Newly created, under evaluation
    RETIRED = auto()         # Manually retired


@dataclass
class RuleEffectiveness:
    """Tracks the effectiveness of a single rule over time."""
    total_matches: int = 0
    confirmed_true_positives: int = 0
    confirmed_false_positives: int = 0
    pending_review: int = 0
    last_match_timestamp: float = 0.0
    created_timestamp: float = field(default_factory=time.time)

    @property
    def true_positive_rate(self) -> float:
        confirmed = self.confirmed_true_positives + self.confirmed_false_positives
        if confirmed == 0:
            return 0.5  # Unknown = neutral
        return self.confirmed_true_positives / confirmed

    @property
    def false_positive_rate(self) -> float:
        confirmed = self.confirmed_true_positives + self.confirmed_false_positives
        if confirmed == 0:
            return 0.0
        return self.confirmed_false_positives / confirmed

    def to_dict(self) -> dict:
        return {
            "total_matches": self.total_matches,
            "confirmed_true_positives": self.confirmed_true_positives,
            "confirmed_false_positives": self.confirmed_false_positives,
            "pending_review": self.pending_review,
            "last_match_timestamp": self.last_match_timestamp,
            "created_timestamp": self.created_timestamp,
            "true_positive_rate": round(self.true_positive_rate, 3),
            "false_positive_rate": round(self.false_positive_rate, 3),
        }

    @classmethod
    def from_dict(cls, data: dict) -> "RuleEffectiveness":
        return cls(
            total_matches=data.get("total_matches", 0),
            confirmed_true_positives=data.get("confirmed_true_positives", 0),
            confirmed_false_positives=data.get("confirmed_false_positives", 0),
            pending_review=data.get("pending_review", 0),
            last_match_timestamp=data.get("last_match_timestamp", 0.0),
            created_timestamp=data.get("created_timestamp", time.time()),
        )


@dataclass
class DynamicRule:
    """
    A single dynamic analysis rule.

    Rules can be loaded from config files or generated programmatically
    by the adaptive learning or internet discovery systems.
    """
    rule_id: str
    name: str
    description: str
    pattern: str                     # Regex pattern
    vuln_class: int                  # Maps to CWE via cwe_mapping
    severity: str = "medium"         # critical, high, medium, low
    confidence: float = 0.6          # Base confidence for matches
    languages: list = field(default_factory=list)  # Empty = all languages
    frameworks: list = field(default_factory=list)  # Empty = all frameworks
    conditions: dict = field(default_factory=dict)  # Extra match conditions
    status: RuleStatus = RuleStatus.ACTIVE
    source: str = "config"           # config, adaptive, internet, manual
    tags: list = field(default_factory=list)
    effectiveness: RuleEffectiveness = field(default_factory=RuleEffectiveness)
    priority: float = 1.0            # Adaptive priority multiplier

    @property
    def is_active(self) -> bool:
        return self.status in (RuleStatus.ACTIVE, RuleStatus.PROMOTED, RuleStatus.EXPERIMENTAL)

    def matches_language(self, language: str) -> bool:
        if not self.languages:
            return True
        return language.lower() in [l.lower() for l in self.languages]

    def matches_framework(self, framework: str) -> bool:
        if not self.frameworks:
            return True
        return framework.lower() in [f.lower() for f in self.frameworks]

    def to_dict(self) -> dict:
        return {
            "rule_id": self.rule_id,
            "name": self.name,
            "description": self.description,
            "pattern": self.pattern,
            "vuln_class": self.vuln_class,
            "severity": self.severity,
            "confidence": self.confidence,
            "languages": self.languages,
            "frameworks": self.frameworks,
            "conditions": self.conditions,
            "status": self.status.name,
            "source": self.source,
            "tags": self.tags,
            "effectiveness": self.effectiveness.to_dict(),
            "priority": self.priority,
        }

    @classmethod
    def from_dict(cls, data: dict) -> "DynamicRule":
        eff_data = data.get("effectiveness", {})
        status_name = data.get("status", "ACTIVE")
        try:
            status = RuleStatus[status_name]
        except KeyError:
            status = RuleStatus.ACTIVE

        return cls(
            rule_id=data.get("rule_id", ""),
            name=data.get("name", ""),
            description=data.get("description", ""),
            pattern=data.get("pattern", ""),
            vuln_class=data.get("vuln_class", 9),
            severity=data.get("severity", "medium"),
            confidence=data.get("confidence", 0.6),
            languages=data.get("languages", []),
            frameworks=data.get("frameworks", []),
            conditions=data.get("conditions", {}),
            status=status,
            source=data.get("source", "config"),
            tags=data.get("tags", []),
            effectiveness=RuleEffectiveness.from_dict(eff_data),
            priority=data.get("priority", 1.0),
        )


class DynamicRuleEngine:
    """
    Hot-loadable dynamic rule engine with self-tuning capabilities.

    Loads rules from configuration files, tracks their effectiveness,
    and automatically adjusts rule priority and status based on
    observed true/false positive rates.
    """

    DEFAULT_RULES_DIR = os.path.expanduser("~/.bayreuthwing/dynamic_rules")
    AUTO_DISABLE_FP_THRESHOLD = 0.5    # Disable rules with >50% FP rate
    AUTO_PROMOTE_TP_THRESHOLD = 0.8    # Promote rules with >80% TP rate
    MIN_SAMPLES_FOR_AUTO_TUNE = 10     # Need N samples before auto-tuning

    def __init__(
        self,
        rules_dir: str | None = None,
        auto_disable_threshold: float = 0.5,
        auto_promote_threshold: float = 0.8,
    ):
        self.rules_dir = rules_dir or self.DEFAULT_RULES_DIR
        self.auto_disable_threshold = auto_disable_threshold
        self.auto_promote_threshold = auto_promote_threshold
        self.rules: dict[str, DynamicRule] = {}
        self._compiled_patterns: dict[str, re.Pattern] = {}

        # Load built-in rules
        self._load_builtin_rules()

        # Load from config directory
        self._load_rules_from_dir()

    def _load_builtin_rules(self):
        """Load built-in dynamic rules for the expanded vulnerability classes."""
        builtin_rules = [
            # ── XXE (11) ──
            DynamicRule(
                rule_id="DYN-XXE-001", name="XXE via DTD Declaration",
                description="XML parser with external entity processing enabled",
                pattern=r'<!DOCTYPE\s+\w+\s+\[.*<!ENTITY',
                vuln_class=11, severity="high", confidence=0.85,
                tags=["xxe", "xml", "injection"],
            ),
            DynamicRule(
                rule_id="DYN-XXE-002", name="Unsafe XML Parser Configuration",
                description="XML parser without disabling external entities",
                pattern=r'(?:etree\.parse|xml\.dom\.minidom\.parse|SAXParser|DocumentBuilder)(?!.*(?:defused|safe|disable.*external|FEATURE_EXTERNAL))',
                vuln_class=11, severity="high", confidence=0.7,
                languages=["python", "java"],
                tags=["xxe", "xml", "configuration"],
            ),
            # ── LDAP Injection (12) ──
            DynamicRule(
                rule_id="DYN-LDAP-001", name="LDAP Query with User Input",
                description="LDAP search filter constructed with string formatting",
                pattern=r'(?:ldap\.search|search_s|search_ext)\s*\(.*(?:format|%s|\+\s*\w+|f["\'])',
                vuln_class=12, severity="high", confidence=0.8,
                tags=["ldap", "injection"],
            ),
            # ── XPath Injection (13) ──
            DynamicRule(
                rule_id="DYN-XPATH-001", name="XPath with String Concatenation",
                description="XPath query built using string concatenation with user input",
                pattern=r'\.xpath\s*\(.*(?:format|%s|\+\s*\w+|f["\'])',
                vuln_class=13, severity="high", confidence=0.8,
                tags=["xpath", "injection"],
            ),
            # ── SSTI (14) ──
            DynamicRule(
                rule_id="DYN-SSTI-001", name="Template Render with User Input",
                description="Template rendered with unsanitized user input",
                pattern=r'(?:render_template_string|Template\s*\(|Environment\(\)).*(?:request\.|params\[|user_input)',
                vuln_class=14, severity="critical", confidence=0.85,
                tags=["ssti", "template", "injection"],
            ),
            DynamicRule(
                rule_id="DYN-SSTI-002", name="Jinja2/Django Template Injection",
                description="User input directly in template context",
                pattern=r'(?:render_template_string|Template)\s*\(\s*(?:request\.|f["\']|.*\+)',
                vuln_class=14, severity="critical", confidence=0.8,
                languages=["python"],
                tags=["ssti", "jinja2", "django"],
            ),
            # ── HTTP Header Injection (15) ──
            DynamicRule(
                rule_id="DYN-HDR-001", name="Header Value from User Input",
                description="HTTP response header set with unsanitized user input",
                pattern=r'(?:set_header|add_header|response\.headers|setHeader)\s*\([^)]*(?:request\.|params\[|user)',
                vuln_class=15, severity="medium", confidence=0.7,
                tags=["header", "injection"],
            ),
            # ── CRLF Injection (16) ──
            DynamicRule(
                rule_id="DYN-CRLF-001", name="CRLF in Response",
                description="User input in HTTP response without CRLF stripping",
                pattern=r'(?:response\.write|print|echo)\s*\(.*(?:request\.|params\[|GET\[|POST\[)',
                vuln_class=16, severity="medium", confidence=0.6,
                tags=["crlf", "injection"],
            ),
            # ── Log Injection (17) ──
            DynamicRule(
                rule_id="DYN-LOG-001", name="Unsanitized Log Input",
                description="User input logged without sanitization",
                pattern=r'(?:logger?\.\w+|logging\.\w+|console\.log|System\.out\.print)\s*\(.*(?:request\.|params\[|user_input|req\.)',
                vuln_class=17, severity="medium", confidence=0.65,
                tags=["log", "injection"],
            ),
            # ── Prototype Pollution (18) ──
            DynamicRule(
                rule_id="DYN-PROTO-001", name="Deep Merge with User Input",
                description="Recursive object merge with user-controlled data",
                pattern=r'(?:merge|extend|assign|deepMerge|defaults)\s*\([^)]*(?:req\.|body\.|params\[|query\.)',
                vuln_class=18, severity="high", confidence=0.75,
                languages=["javascript", "typescript"],
                tags=["prototype", "pollution", "javascript"],
            ),
            DynamicRule(
                rule_id="DYN-PROTO-002", name="__proto__ Access Pattern",
                description="Direct access to __proto__ or constructor.prototype",
                pattern=r'(?:__proto__|constructor\s*\[\s*["\']prototype["\']|Object\.setPrototypeOf)',
                vuln_class=18, severity="high", confidence=0.85,
                languages=["javascript", "typescript"],
                tags=["prototype", "pollution"],
            ),
            # ── Race Condition (19) ──
            DynamicRule(
                rule_id="DYN-RACE-001", name="Check-then-Act Pattern",
                description="File existence check followed by file operation (TOCTOU)",
                pattern=r'(?:os\.path\.exists|Path\(.*\)\.exists|File\.exists)\s*\(.*\)[\s\S]{0,100}(?:open|read|write|unlink|remove)',
                vuln_class=19, severity="high", confidence=0.7,
                tags=["race", "toctou", "filesystem"],
            ),
            # ── Integer Overflow (20) ──
            DynamicRule(
                rule_id="DYN-INT-001", name="Unchecked Integer Arithmetic",
                description="Integer arithmetic without overflow check in C/C++",
                pattern=r'(?:int|short|unsigned)\s+\w+\s*=\s*\w+\s*[\+\*]\s*\w+',
                vuln_class=20, severity="high", confidence=0.6,
                languages=["c", "cpp"],
                tags=["integer", "overflow", "memory"],
            ),
            # ── Use After Free (21) ──
            DynamicRule(
                rule_id="DYN-UAF-001", name="Use After Free Pattern",
                description="Variable used after free/delete",
                pattern=r'(?:free|delete)\s*\(\s*(\w+)\s*\)[\s\S]{0,200}\1\s*(?:->|\[|\.|=)',
                vuln_class=21, severity="critical", confidence=0.7,
                languages=["c", "cpp"],
                tags=["memory", "use-after-free"],
            ),
            # ── Null Dereference (22) ──
            DynamicRule(
                rule_id="DYN-NULL-001", name="Null Dereference Pattern",
                description="Pointer dereferenced without null check",
                pattern=r'(?:NULL|nullptr|null)\s*(?:;|,)[\s\S]{0,100}(?:->|\.\w+\()',
                vuln_class=22, severity="medium", confidence=0.55,
                languages=["c", "cpp", "java", "csharp"],
                tags=["null", "dereference"],
            ),
            # ── Open Redirect (23) ──
            DynamicRule(
                rule_id="DYN-REDIR-001", name="Open Redirect via Parameter",
                description="Redirect using user-controlled URL parameter",
                pattern=r'(?:redirect|sendRedirect|res\.redirect|location\.href|window\.location)\s*(?:\(|=)\s*(?:request\.|params\[|req\.query|GET\[|url_param)',
                vuln_class=23, severity="medium", confidence=0.75,
                tags=["redirect", "open-redirect"],
            ),
            # ── CORS Misconfiguration (24) ──
            DynamicRule(
                rule_id="DYN-CORS-001", name="Wildcard CORS Origin",
                description="CORS Access-Control-Allow-Origin set to wildcard",
                pattern=r'(?:Access-Control-Allow-Origin|allowOrigin|cors\.origin)\s*[:=]\s*["\']?\*["\']?',
                vuln_class=24, severity="medium", confidence=0.8,
                tags=["cors", "misconfiguration"],
            ),
            DynamicRule(
                rule_id="DYN-CORS-002", name="Reflected CORS Origin",
                description="CORS origin reflected from request header",
                pattern=r'(?:Access-Control-Allow-Origin|allowOrigin)\s*[:=]\s*(?:request\.|req\.|origin|headers\[)',
                vuln_class=24, severity="high", confidence=0.8,
                tags=["cors", "misconfiguration"],
            ),
            # ── JWT Vulnerabilities (25) ──
            DynamicRule(
                rule_id="DYN-JWT-001", name="JWT None Algorithm",
                description="JWT verification allows 'none' algorithm",
                pattern=r'(?:algorithms?\s*[:=]\s*\[.*["\'](?:none|None|NONE)["\']|verify\s*[:=]\s*(?:false|False))',
                vuln_class=25, severity="critical", confidence=0.9,
                tags=["jwt", "authentication"],
            ),
            DynamicRule(
                rule_id="DYN-JWT-002", name="Weak JWT Secret",
                description="JWT signed with weak or hardcoded secret",
                pattern=r'(?:jwt\.(?:encode|sign))\s*\([^)]*["\'](?:secret|password|key123|changeme|admin)["\']',
                vuln_class=25, severity="high", confidence=0.85,
                tags=["jwt", "credentials"],
            ),
            # ── OAuth Misconfiguration (26) ──
            DynamicRule(
                rule_id="DYN-OAUTH-001", name="Missing OAuth State Parameter",
                description="OAuth flow without CSRF state parameter",
                pattern=r'(?:authorize|authorization_url|oauth/authorize)(?!.*state)',
                vuln_class=26, severity="high", confidence=0.65,
                tags=["oauth", "csrf"],
            ),
            # ── Mass Assignment (27) ──
            DynamicRule(
                rule_id="DYN-MASS-001", name="Direct Model Binding",
                description="Request data bound directly to model without filtering",
                pattern=r'(?:\.objects\.create\s*\(\s*\*\*request\.|\.update\s*\(\s*\*\*request\.|Model\.from_json\s*\(.*request)',
                vuln_class=27, severity="high", confidence=0.8,
                languages=["python"],
                tags=["mass-assignment"],
            ),
            # ── IDOR / BOLA (28) ──
            DynamicRule(
                rule_id="DYN-IDOR-001", name="Sequential ID in URL Pattern",
                description="Endpoint using sequential numeric ID without auth check",
                pattern=r'(?:route|path|get|post)\s*\(\s*["\'][^"\']*<int:\w*id>|/\d+["\']',
                vuln_class=28, severity="high", confidence=0.6,
                tags=["idor", "bola", "access-control"],
            ),
            # ── Dependency Confusion (30) ──
            DynamicRule(
                rule_id="DYN-DEPCONF-001", name="Private Package Without Scope",
                description="Internal package name without namespace/scope protection",
                pattern=r'(?:--extra-index-url|--index-url)\s+https?://(?!pypi\.org|registry\.npmjs)',
                vuln_class=30, severity="critical", confidence=0.7,
                tags=["supply-chain", "dependency-confusion"],
            ),
            # ── ReDoS (31) ──
            DynamicRule(
                rule_id="DYN-REDOS-001", name="Evil Regex Pattern",
                description="Regex with catastrophic backtracking potential",
                pattern=r're\.(?:compile|match|search|findall)\s*\([^)]*(?:\(\w+\+\)\+|\(\w+\|\w+\)\*|\[\^[^\]]+\]\+\w+\+)',
                vuln_class=31, severity="medium", confidence=0.7,
                languages=["python", "javascript"],
                tags=["redos", "regex", "dos"],
            ),
            # ── Session Fixation (32) ──
            DynamicRule(
                rule_id="DYN-SESSFIX-001", name="Missing Session Regeneration",
                description="Authentication without session ID regeneration",
                pattern=r'(?:login|authenticate|sign_in)(?![\s\S]{0,200}(?:regenerate|new_session|invalidate|flush))',
                vuln_class=32, severity="high", confidence=0.6,
                tags=["session", "fixation", "authentication"],
            ),
            # ── Clickjacking (33) ──
            DynamicRule(
                rule_id="DYN-CLICK-001", name="Missing Frame Protection",
                description="No X-Frame-Options or CSP frame-ancestors header",
                pattern=r'(?:app\.run|listen\s*\()(?![\s\S]{0,500}(?:X-Frame-Options|frame-ancestors))',
                vuln_class=33, severity="medium", confidence=0.5,
                tags=["clickjacking", "headers"],
            ),
            # ── Insecure File Upload (34) ──
            DynamicRule(
                rule_id="DYN-UPLOAD-001", name="File Upload Without Validation",
                description="File upload handler without type/size validation",
                pattern=r'(?:file\.save|upload|multer|formidable|request\.FILES)(?![\s\S]{0,200}(?:allowed_extensions|content_type|validate|check_file))',
                vuln_class=34, severity="high", confidence=0.65,
                tags=["file-upload", "validation"],
            ),
        ]

        for rule in builtin_rules:
            self.rules[rule.rule_id] = rule
            self._compile_pattern(rule)

    def _compile_pattern(self, rule: DynamicRule):
        """Compile and cache a rule's regex pattern."""
        try:
            self._compiled_patterns[rule.rule_id] = re.compile(
                rule.pattern, re.IGNORECASE | re.MULTILINE
            )
        except re.error:
            rule.status = RuleStatus.DISABLED

    def _load_rules_from_dir(self):
        """Load rules from the configuration directory."""
        if not os.path.exists(self.rules_dir):
            return

        for filename in os.listdir(self.rules_dir):
            if filename.endswith((".json", ".yaml", ".yml")):
                filepath = os.path.join(self.rules_dir, filename)
                try:
                    with open(filepath, "r", encoding="utf-8") as f:
                        if filename.endswith(".json"):
                            data = json.load(f)
                        else:
                            try:
                                import yaml
                                data = yaml.safe_load(f)
                            except ImportError:
                                continue

                    rules_data = data.get("rules", [data] if "rule_id" in data else [])
                    for rule_data in rules_data:
                        rule = DynamicRule.from_dict(rule_data)
                        self.rules[rule.rule_id] = rule
                        self._compile_pattern(rule)
                except (json.JSONDecodeError, KeyError, TypeError, OSError):
                    pass

    def scan(self, code: str, language: str, framework: str = "") -> list[dict]:
        """
        Scan code using all active dynamic rules.

        Args:
            code: Source code to scan.
            language: Programming language.
            framework: Detected framework (optional).

        Returns:
            List of finding dictionaries.
        """
        findings = []

        for rule_id, rule in self.rules.items():
            if not rule.is_active:
                continue

            if not rule.matches_language(language):
                continue

            if framework and not rule.matches_framework(framework):
                continue

            compiled = self._compiled_patterns.get(rule_id)
            if compiled is None:
                continue

            for match in compiled.finditer(code):
                line = code[:match.start()].count("\n") + 1
                matched_text = match.group(0)[:100]

                findings.append({
                    "vuln_class": rule.vuln_class,
                    "severity": rule.severity,
                    "confidence": rule.confidence * rule.priority,
                    "line": line,
                    "message": f"[{rule.rule_id}] {rule.name}: {rule.description}",
                    "matched_text": matched_text,
                    "source": f"dynamic_rule:{rule.source}",
                    "rule_id": rule.rule_id,
                    "tags": rule.tags,
                })

                # Track effectiveness
                rule.effectiveness.total_matches += 1
                rule.effectiveness.last_match_timestamp = time.time()
                rule.effectiveness.pending_review += 1

        return findings

    def record_feedback(self, rule_id: str, is_true_positive: bool):
        """Record human/automated feedback on a rule's match."""
        if rule_id not in self.rules:
            return

        rule = self.rules[rule_id]
        if is_true_positive:
            rule.effectiveness.confirmed_true_positives += 1
        else:
            rule.effectiveness.confirmed_false_positives += 1

        if rule.effectiveness.pending_review > 0:
            rule.effectiveness.pending_review -= 1

        # Auto-tune
        self._auto_tune_rule(rule)

    def _auto_tune_rule(self, rule: DynamicRule):
        """Automatically adjust rule status based on effectiveness."""
        total_confirmed = (
            rule.effectiveness.confirmed_true_positives +
            rule.effectiveness.confirmed_false_positives
        )

        if total_confirmed < self.MIN_SAMPLES_FOR_AUTO_TUNE:
            return

        if rule.effectiveness.false_positive_rate > self.auto_disable_threshold:
            rule.status = RuleStatus.DISABLED

        elif rule.effectiveness.true_positive_rate > self.auto_promote_threshold:
            rule.status = RuleStatus.PROMOTED
            rule.priority = min(2.0, rule.priority * 1.2)

    def add_rule(self, rule: DynamicRule):
        """Add a new rule to the engine."""
        rule.status = RuleStatus.EXPERIMENTAL
        self.rules[rule.rule_id] = rule
        self._compile_pattern(rule)

    def hot_reload(self):
        """Reload rules from the configuration directory."""
        self._load_rules_from_dir()

    def get_stats(self) -> dict:
        """Get engine statistics."""
        active = sum(1 for r in self.rules.values() if r.is_active)
        disabled = sum(1 for r in self.rules.values() if r.status == RuleStatus.DISABLED)
        promoted = sum(1 for r in self.rules.values() if r.status == RuleStatus.PROMOTED)
        total_matches = sum(r.effectiveness.total_matches for r in self.rules.values())

        return {
            "total_rules": len(self.rules),
            "active_rules": active,
            "disabled_rules": disabled,
            "promoted_rules": promoted,
            "total_matches": total_matches,
            "rules_by_source": self._count_by_source(),
        }

    def _count_by_source(self) -> dict:
        counts = {}
        for rule in self.rules.values():
            counts[rule.source] = counts.get(rule.source, 0) + 1
        return counts

    @property
    def total_rules(self) -> int:
        return len(self.rules)
